Docs UI update
solana-foundation/solana-com pull request #3
Opened 2024-07-30 17:34 UTC by ZYJLiu

1. Add Tabs/Tab component
![CleanShot 2024-07-30 at 12 25 18](https://github.com/user-attachments/assets/88a51d98-4861-4d14-9ba3-394165319ee6)

Example usage on developer-content md files:
```md

<Tabs groupId="language" items={['Rust', 'Typescript', 'Java']}>
<Tab value="Rust">Rust 1</Tab>
<Tab value="Typescript">Typescript 1</Tab>
<Tab value="Java">Java</Tab>
</Tabs>

<Tabs groupId="language" items={['Rust', 'Typescript', 'Go']}>
<Tab value="Rust">Rust 2</Tab>
<Tab value="Typescript">Typescript 2</Tab>
<Tab value="Go">Go</Tab>
</Tabs>

<Tabs groupId="package-managers" items={['pnpm', 'npm', 'yarn']}>
<Tab value="pnpm">pnpm 1</Tab> 
<Tab value="npm">npm 1</Tab>
<Tab value="yarn">yarn 1</Tab> 
</Tabs>

<Tabs groupId="package-managers" items={['pnpm', 'npm', 'yarn']}>
<Tab value="pnpm">pnpm 2</Tab> 
<Tab value="npm">npm 2</Tab>
<Tab value="yarn">yarn 2</Tab> 
</Tabs>
```
2. Add Accordion/AccordionItem component

![CleanShot 2024-07-30 at 12 27 32](https://github.com/user-attachments/assets/565db71d-3e8b-4b47-b541-a8a21e2c6fa4)

Example usage on developer-content md files:

````md
  <Accordion>
  <AccordionItem title="Hello">
  
  ```ts
  console.log("hello");
  ```
  
  </AccordionItem>
  <AccordionItem title="World">
  
  ```rs
  println!("world");
  ```
  
  </AccordionItem>
  </Accordion>
````

3. Update docs codeblock UI with svgs icons in header
![CleanShot 2024-07-30 at 12 20 40@2x](https://github.com/user-attachments/assets/000472a2-16a4-4eef-bc25-acfeabbd957c)

4. Add lightmode color to docs components/codeblock
![CleanShot 2024-07-30 at 12 21 46@2x](https://github.com/user-attachments/assets/4644aa98-7bfd-40b9-96db-2b22b3c57adf)
![CleanShot 2024-07-30 at 12 28 20@2x](https://github.com/user-attachments/assets/1c7d9c95-dea4-417a-a918-99a28e7e2f52)
![CleanShot 2024-07-30 at 12 29 56@2x](https://github.com/user-attachments/assets/3407a69d-d956-488b-a705-8cfe9c45796d)

5. Update docs scrollbar to only appear on hover
![CleanShot 2024-07-30 at 12 31 06](https://github.com/user-attachments/assets/b39aeaf3-738f-4a98-abb5-5e1b88b8ac7d)

2024-07-31 19:19 UTC, nickfrosty requested changes
great work here John! the new components will be a great addition to the site. better UX all around! :)

I just have the one concern about the regex fix for other languages. we need to find a different solution

2024-07-31 19:19 UTC, nickfrosty commented on src/utils/contentApi.ts
> +        label = label.replace(/[^a-zA-Z0-9]+$/, "");
updating this regex to your suggesest change will break all translated content within the table of contents. and maybe prevent the site from building.

we need to find a different solution to solve the "trailing L" bug we are seeing

2024-07-31 19:19 UTC, nickfrosty commented on src/utils/contentApi.ts
> +        .replace(/[^a-z0-9]+/g, "-")
same comment as above

2024-07-31 19:19 UTC, nickfrosty commented on src/components/developers/DevelopersNav/DevelopersNav.jsx
> +import StackExchangeIcon from "../../../../assets/developers/stackexchange.inline.svg";
can we cleanup these relative paths by using `@@/public/**`? either in this PR or a different one?

2024-07-31 19:21 UTC, mikemaccana requested changes
Please add the usage guidelines for the new components (in the text of this PR) into `CONTRIBUTING.md`

2024-07-31 20:35 UTC, ZYJLiu commented on src/components/developers/DevelopersNav/DevelopersNav.jsx
> +import StackExchangeIcon from "../../../../assets/developers/stackexchange.inline.svg";
updated

2024-08-01 14:50 UTC, ZYJLiu commented
> Please add the usage guidelines for the new components (you've already added them in the text of this PR) into `CONTRIBUTING.md`

will add to developer-content, since that is where the components are used

2024-08-01 16:02 UTC, nickfrosty approved these changes
Great work on this John. I think people are going to really like these new UX improvements

2024-08-01 16:05 UTC, nickfrosty commented
> Please add the usage guidelines for the new components (you've already added them in the text of this PR) into `CONTRIBUTING.md`

added tracking issue on dev content: https://github.com/solana-foundation/developer-content/issues/288

2024-08-01 16:05 UTC, merged

2024-08-09 17:23 UTC, mikemaccana commented on src/utils/contentApi.ts
> +        label = label.replace(/[^\p{L}\p{N}]+$/u, "");
BTW @ZYJLiu you can use `\p{Letter}` and `\p{Number}` to make the unicode bits more obvious. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Unicode_character_class_escape