Add enkrypt wallet
solana-foundation/solana-com pull request #82
Opened 2024-10-31 00:19 UTC by Abyscuit

request for review to add Enkrypt Wallet to https://solana.com/solana-wallets

2024-10-31 09:35 UTC, catalinred commented
@Abyscuit I took a quick look at the wallet’s repo, supported chains on the website, and the documentation, but I didn’t see any mention of existing support for the Solana blockchain.

It looks like the support for Solana was recently added and this might explain it. Could you open an issue once you've addressed the comments above? That way, we can continue the discussion there and proceed with a review for this PR afterwards. Thank you.

2024-11-20 06:19 UTC, catalinred requested changes
@Abyscuit We reviewed the submission and before merging this to `main`, could you move the Encrypt object to the end of the `walletData` array?

2024-11-20 23:34 UTC, Abyscuit commented
@catalinred I have moved the object to the end of walletData.

2024-11-21 12:22 UTC, catalinred approved these changes

2024-11-21 12:23 UTC, merged